# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7aae87bbb7ccda522ef3c67e2d2df7ce2694e3118b01113e4c2314f3ff19404bb8515724032a06c320abc16685f6638a1672da81c346d94c3ad97430424774f
  nevernote_api_base: localhost:3000/api/v1/

test:
  secret_key_base: ab9056380e8f7ecdea51ac449194f8857f5cec4813d50e91c0008f36a90105c85c6181fa571f566d933713e2951fa76f5d8184dc5d181e6d31a82136332d20b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
